"""Initial tables

Revision ID: fb5dae719aae
Revises: 
Create Date: 2025-03-27 01:21:16.695611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb5dae719aae'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video_links',
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('destination_url', sa.String(length=1024), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_video_links_slug', 'video_links', ['slug'], unique=False)
    op.create_index(op.f('ix_video_links_id'), 'video_links', ['id'], unique=False)
    op.create_index(op.f('ix_video_links_slug'), 'video_links', ['slug'], unique=True)
    op.create_table('calls',
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('booked', 'live', 'no_show', 'rescheduled', name='callstatus', native_enum=False), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['slug'], ['video_links.slug'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_calls_email', 'calls', ['email'], unique=False)
    op.create_index('idx_calls_slug', 'calls', ['slug'], unique=False)
    op.create_index('idx_calls_slug_status', 'calls', ['slug', 'status'], unique=False)
    op.create_index('idx_calls_status', 'calls', ['status'], unique=False)
    op.create_index('idx_calls_timestamp', 'calls', ['timestamp'], unique=False)
    op.create_index(op.f('ix_calls_email'), 'calls', ['email'], unique=False)
    op.create_index(op.f('ix_calls_id'), 'calls', ['id'], unique=False)
    op.create_index(op.f('ix_calls_slug'), 'calls', ['slug'], unique=False)
    op.create_index(op.f('ix_calls_status'), 'calls', ['status'], unique=False)
    op.create_index(op.f('ix_calls_timestamp'), 'calls', ['timestamp'], unique=False)
    op.create_table('clicks',
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('referrer', sa.String(length=1024), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['slug'], ['video_links.slug'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_clicks_slug', 'clicks', ['slug'], unique=False)
    op.create_index('idx_clicks_slug_timestamp', 'clicks', ['slug', 'timestamp'], unique=False)
    op.create_index('idx_clicks_timestamp', 'clicks', ['timestamp'], unique=False)
    op.create_index(op.f('ix_clicks_id'), 'clicks', ['id'], unique=False)
    op.create_index(op.f('ix_clicks_slug'), 'clicks', ['slug'], unique=False)
    op.create_index(op.f('ix_clicks_timestamp'), 'clicks', ['timestamp'], unique=False)
    op.create_table('payments',
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['slug'], ['video_links.slug'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_payments_email', 'payments', ['email'], unique=False)
    op.create_index('idx_payments_slug', 'payments', ['slug'], unique=False)
    op.create_index('idx_payments_slug_email', 'payments', ['slug', 'email'], unique=False)
    op.create_index('idx_payments_timestamp', 'payments', ['timestamp'], unique=False)
    op.create_index(op.f('ix_payments_email'), 'payments', ['email'], unique=False)
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    op.create_index(op.f('ix_payments_slug'), 'payments', ['slug'], unique=False)
    op.create_index(op.f('ix_payments_timestamp'), 'payments', ['timestamp'], unique=False)
    op.create_table('video_analytics',
    sa.Column('video_id', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('views', sa.Integer(), nullable=False),
    sa.Column('likes', sa.Integer(), nullable=False),
    sa.Column('comments', sa.Integer(), nullable=False),
    sa.Column('engagement_rate', sa.Float(), nullable=False),
    sa.Column('avg_view_duration', sa.Float(), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['slug'], ['video_links.slug'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_video_analytics_last_updated', 'video_analytics', ['last_updated'], unique=False)
    op.create_index('idx_video_analytics_slug', 'video_analytics', ['slug'], unique=False)
    op.create_index('idx_video_analytics_video_id', 'video_analytics', ['video_id'], unique=False)
    op.create_index(op.f('ix_video_analytics_id'), 'video_analytics', ['id'], unique=False)
    op.create_index(op.f('ix_video_analytics_last_updated'), 'video_analytics', ['last_updated'], unique=False)
    op.create_index(op.f('ix_video_analytics_slug'), 'video_analytics', ['slug'], unique=False)
    op.create_index(op.f('ix_video_analytics_video_id'), 'video_analytics', ['video_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_video_analytics_video_id'), table_name='video_analytics')
    op.drop_index(op.f('ix_video_analytics_slug'), table_name='video_analytics')
    op.drop_index(op.f('ix_video_analytics_last_updated'), table_name='video_analytics')
    op.drop_index(op.f('ix_video_analytics_id'), table_name='video_analytics')
    op.drop_index('idx_video_analytics_video_id', table_name='video_analytics')
    op.drop_index('idx_video_analytics_slug', table_name='video_analytics')
    op.drop_index('idx_video_analytics_last_updated', table_name='video_analytics')
    op.drop_table('video_analytics')
    op.drop_index(op.f('ix_payments_timestamp'), table_name='payments')
    op.drop_index(op.f('ix_payments_slug'), table_name='payments')
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_email'), table_name='payments')
    op.drop_index('idx_payments_timestamp', table_name='payments')
    op.drop_index('idx_payments_slug_email', table_name='payments')
    op.drop_index('idx_payments_slug', table_name='payments')
    op.drop_index('idx_payments_email', table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_clicks_timestamp'), table_name='clicks')
    op.drop_index(op.f('ix_clicks_slug'), table_name='clicks')
    op.drop_index(op.f('ix_clicks_id'), table_name='clicks')
    op.drop_index('idx_clicks_timestamp', table_name='clicks')
    op.drop_index('idx_clicks_slug_timestamp', table_name='clicks')
    op.drop_index('idx_clicks_slug', table_name='clicks')
    op.drop_table('clicks')
    op.drop_index(op.f('ix_calls_timestamp'), table_name='calls')
    op.drop_index(op.f('ix_calls_status'), table_name='calls')
    op.drop_index(op.f('ix_calls_slug'), table_name='calls')
    op.drop_index(op.f('ix_calls_id'), table_name='calls')
    op.drop_index(op.f('ix_calls_email'), table_name='calls')
    op.drop_index('idx_calls_timestamp', table_name='calls')
    op.drop_index('idx_calls_status', table_name='calls')
    op.drop_index('idx_calls_slug_status', table_name='calls')
    op.drop_index('idx_calls_slug', table_name='calls')
    op.drop_index('idx_calls_email', table_name='calls')
    op.drop_table('calls')
    op.drop_index(op.f('ix_video_links_slug'), table_name='video_links')
    op.drop_index(op.f('ix_video_links_id'), table_name='video_links')
    op.drop_index('idx_video_links_slug', table_name='video_links')
    op.drop_table('video_links')
    # ### end Alembic commands ### 