"""ensure_extra_data_field

Revision ID: 91a36b4dbacb
Revises: 5e47451ddd64
Create Date: 2025-03-29 01:44:36.908127

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '91a36b4dbacb'
down_revision = '5e47451ddd64'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('integrations', sa.Column('extra_data', sa.JSON(), nullable=True))
    op.drop_index('ix_integrations_new_id', table_name='integrations')
    op.create_index(op.f('ix_integrations_account_id'), 'integrations', ['account_id'], unique=False)
    op.create_index(op.f('ix_integrations_id'), 'integrations', ['id'], unique=False)
    op.create_index(op.f('ix_integrations_user_id'), 'integrations', ['user_id'], unique=False)
    op.drop_column('integrations', 'metadata')
    op.drop_index('idx_payments_dashboard_user', table_name='payments')
    op.drop_index('idx_payments_stripe_account', table_name='payments')
    op.create_index(op.f('ix_payments_dashboard_user_id'), 'payments', ['dashboard_user_id'], unique=False)
    op.create_index(op.f('ix_payments_stripe_account_id'), 'payments', ['stripe_account_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_stripe_account_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_dashboard_user_id'), table_name='payments')
    op.create_index('idx_payments_stripe_account', 'payments', ['stripe_account_id'], unique=False)
    op.create_index('idx_payments_dashboard_user', 'payments', ['dashboard_user_id'], unique=False)
    op.add_column('integrations', sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_integrations_user_id'), table_name='integrations')
    op.drop_index(op.f('ix_integrations_id'), table_name='integrations')
    op.drop_index(op.f('ix_integrations_account_id'), table_name='integrations')
    op.create_index('ix_integrations_new_id', 'integrations', ['id'], unique=False)
    op.drop_column('integrations', 'extra_data')
    # ### end Alembic commands ### 